server:
  port: 8005

spring:
  application:
    name: ms-invoice
  datasource:
    #url: jdbc:postgresql://localhost:5432/db_invoice
    url: jdbc:postgresql://bd-postgres12:5432/db_invoice
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
  kafka:
    consumer:
      #bootstrap-servers: localhost:9092
      bootstrap-servers: servicekafka:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: operation-events-invoice

logging:
  level:
    org:
      hibernate:
        sql: debug
